### ISSUE TITLE
SQLiteException

### ISSUE THREAD

**Issue by android-developer-amit** [cometchat-go/android-chat-sdk-demo#1] opened 2018-05-29 12:57 UTC
Caused by: android.database.sqlite.SQLiteException: no such table: ONE_ON_ONE_MESSAGE (code 1): , while compiling: DELETE FROM ONE_ON_ONE_MESSAGE

**Comment by adityagokula2210** [comment] 2018-05-30 13:50
We have tried to replicate this issue at our end but were unable to do so. We suggest you please check if the Instant Run property of Android Studio is enabled. In case the Instant Run Feature is enabled please disable it and try running the app again.

We have also made some changes to the project. Please make sure you download the latest project or take a pull before you test this again.
In case, you still encounter this issue, please provide us with the complete crash logs and the device specifications on which the issue was encountered so that we can replicate this issue.

Hope this helps.

**Comment by porasdhiman** [comment] 2018-07-19 07:50
same issue please solve this

07-19 13:03:39.718 12926-12926/com.inscripts.cometchatsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inscripts.cometchatsample, PID: 12926
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.inscripts.cometchatsample/activities.CometChatActivity}: android.database.sqlite.SQLiteException: no such table: conversation (code 1): , while compiling: SELECT * FROM `conversation` ORDER BY `timestamp` DESC;
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
        at android.app.ActivityThread.access$900(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5438)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
     Caused by: android.database.sqlite.SQLiteException: no such table: conversation (code 1): , while compiling: SELECT * FROM `conversation` ORDER BY `timestamp` DESC;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
        at com.inscripts.orm.SugarRecord.findWithQuery(SourceFile:126)
        at models.Conversation.isConverSationAvailable(SourceFile:85)
        at activities.CometChatActivity.setupTabs(SourceFile:786)
        at activities.CometChatActivity.onCreate(SourceFile:146)
        at android.app.Activity.performCreate(Activity.java:6303)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
        at android.app.ActivityThread.access$900(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5438) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by anantgarg** [comment] 2018-07-19 09:47
We think that the Instant Run feature of Android Studio is enabled. Please disable the same and check in case you still get the error.

This error has also been resolved in our sdk Version 7.5. Please try with the latest version and let us know if you are still facing this issue. You can create a support ticket: https://www.cometchat.com/contact-support as we may need some additional data.

**Comment by anantgarg** [comment] 2018-07-19 09:56
You can upgrade the CometChat to 7.5.0 in the project build.gradle i.e :
compile 'com.inscripts:CometChat:7.5.0'
compile 'com.inscripts:CometChatUI:7.5.0'

**Closed as completed** 2018-08-03 06:40 UTC
